import {uniqBy} from 'lodash';
import {useEffect, useState} from 'react';
import {fetchData} from '../utils/fetchdata';

function useMedia() {
  const [mediaArray, setMediaArray] = useState([]);

  const getMedia = async () => {
    try {
      const mediaData = await fetchData(
        import.meta.env.VITE_MEDIA_API + '/media',
      );

      const uniqueUserIds = uniqBy(mediaData, 'user_id');

      const authApiUrl = import.meta.env.VITE_AUTH_API;
      const userData = await Promise.all(
        uniqueUserIds.map(
          async (item) =>
            await fetchData(`${authApiUrl}/users/${item.user_id}`),
        ),
      );
      const userMap = userData.reduce((map, {user_id, username}) => {
        map[user_id] = username;
        return map;
      }, {});

      const newData = mediaData.map((item) => ({
        ...item,
        username: userMap[item.user_id],
      }));

      setMediaArray(newData);
    } catch (error) {
      console.error('error', error);
    }
  };
  useEffect(() => {
    getMedia();
  }, []);
  const postMedia = async (file, inputs, token) => {
    const url = import.meta.env.VITE_MEDIA_API + '/media';
    const data = {
      ...inputs,
      ...file,
    };
    const fetchOptions = {
      method: 'POST',
      headers: {
        Authorization: `Bearer: ${token}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(data),
    };
    return await fetchData(url, fetchOptions);

    // TODO: create a suitable object for Media API: without media_id, user_id, thumbnail and created_at. All those are generated by the API. See the media API documentation.
    // TODO: post the data to Media API and get the data as MediaResponse
    // TODO: return the data
  };
  return {mediaArray, postMedia};
}

function useAuthentication() {
  const postLogin = async (inputs) => {
    const fetchOptions = {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(inputs),
    };
    return await fetchData(
      import.meta.env.VITE_AUTH_API + '/auth/login',
      fetchOptions,
    );
  };
  return {postLogin};
}

function useUser() {
  const postUser = async (inputs) => {
    const fetchOptions = {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(inputs),
    };
    const userResult = await fetchData(
      import.meta.env.VITE_AUTH_API + '/users',
      fetchOptions,
    );
    return userResult;
  };
  async function getUserByToken(token) {
    const url = import.meta.env.VITE_AUTH_API + '/users/token';
    const fetchOptions = {
      headers: {
        Authorization: 'Bearer: ' + token,
      },
    };

    const userData = await fetchData(url, fetchOptions);
    return {userData};
  }
  return {getUserByToken, postUser};
}
function useFile() {
  const postFile = async (file, token) => {
    const formData = new FormData();
    formData.append('file', file);
    const url = import.meta.env.VITE_UPLOAD_SERVER + '/upload';
    const fetchOptions = {
      method: 'POST',
      headers: {
        Authorization: 'Bearer: ' + token,
      },
      mode: 'cors',
      body: formData,
    };
    const fileData = await fetchData(url, fetchOptions);
    return fileData;
  };

  return {postFile};
}

export {useAuthentication, useMedia, useUser, useFile};
